<?php

namespace RolesBundle\Repository;


use Doctrine\ORM\EntityRepository;
use RolesBundle\Entity\Utilisateur;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository
{

	public function get_voiture(Utilisateur $user)
    {
        $response = $this->createQueryBuilder('v')
	                    ->where("v.proprietaire = ?1")
	                    ->setParameter(1, $user->getId())
	                    ->getQuery()
	                    ->getResult();
	    return $response;
	    
    }

}
