<?php

namespace AnnoncesBundle\Repository;

use RolesBundle\Entity\Utilisateur;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{

public function get_annonces_from_user(Utilisateur $user)
    {
        $response = $this->createQueryBuilder('a')
	                    ->where("a.id_annonceur = ?1")
	                    ->setParameter(1, $user->getId())
	                    ->getQuery()
	                    ->getResult();

	    return $response;
	    
    }

    public function get_annonce_by_villeDep($villeDep)
    {
        $response = $this->createQueryBuilder('a')
	                    ->where("a.villeDep = ?1")
	                    ->setParameter(1, $villeDep)
	                    ->getQuery()
	                    ->getResult();

	    return $response;
	    
    }

    public function count_nb_annonce()
    {
        $response = $this->createQueryBuilder('a')
	                    ->select("COUNT(a)")
	                    ->getQuery()
                        ->getSingleScalarResult();

	    return $response;
	    
    }


}
