<?php

namespace AnnoncesBundle\Repository;
use AnnoncesBundle\Entity\Annonce;
use RolesBundle\Entity\Utilisateur;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
public function get_reservation_by_annonce($id)
    {
        $response = $this->createQueryBuilder('r')
	                    ->where("r.idAnnonce = ?1")
	                    ->setParameter(1, $id)
	                    ->getQuery()
	                    ->getResult();

	    return $response;
	    
    }

    public function get_reservation_by_user($id)
    {
        $response = $this->createQueryBuilder('r')
	                    ->where("r.idUser = ?1")
	                    ->setParameter(1, $id)
	                    ->getQuery()
	                    ->getResult();

	    return $response;
	    
    }


}
